### ISSUE TITLE
Not found in Visual Studio 2019

### ISSUE THREAD

**Issue by ricardomatias** [abmes/SemanticHighlighter#1]
Cannot install it via Marketplace, because the available version is only for Visual Studio 2017.

**Comment by metatem** [comment]
Hi Ricardo
We have published the new version v1.3.0 to the Marketplace.
It should be compatible with VS 2019 Community and above.
I can see it and install it on my VIsual Studio and also I confirmed with other people with VS 2019 that they can use it.
It seems that you have a strange issue and I will need more information to resolve it.

Please give me the exact version of your Visul Studio - community, pro, enterprise.
Also what do you see when you search for “semantic highlighter” in the marketplace.

**Comment by ricardomatias** [comment]
I have Visual Studio 2019 Community Edition, v16.1.3. The first hit is Semantic Colorizer, followed by other packages.

**Comment by metatem** [comment]
Hi Ricardo
I was able to reproduce the problem and I think I've fixed it. It was a versioning problem that was waiting for VS v16.1

Please check if you can see it now and if everything is ok - if so I will close the issue.
