### ISSUE TITLE
It's not working in visual studio 2019

### ISSUE THREAD

**Issue by pastelkona** [abmes/SemanticHighlighter#2]
Hi, it's not working in visual studio 2019.
Is my setting bad?
My visual studio version is 「16.3.8」.

**Comment by metatem** [comment]
Hi
What do you mean "it's not working". Can you install it?
Or after installation the colors are not applied?

Which edition of VS do you have - Community / Pro / Enterprise?

I can successfully install it on VS 16.3.8 (Ent) and the settings are available under Fonts & Colors.
![image](https://user-images.githubusercontent.com/10722356/68470244-55377f00-0224-11ea-96ac-7cf646431030.png)
![image](https://user-images.githubusercontent.com/10722356/68470303-71d3b700-0224-11ea-989c-72ef3fdee000.png)

**Comment by pastelkona** [comment]
I can install it. 
The settings are displayed. But the setting is not reflected.

**Comment by metatem** [comment]
Are you using it for C# files?

**Comment by pastelkona** [comment]
Oh, sorry I was trying to use it in the C++ file.
